### ISSUE TITLE
2gis hangs with context leak

### ISSUE THREAD

**Issue by shlyakpavel** [LadybirdBrowser/ladybird#2291]
### Summary

When I open https://2gis.ru/moscow, browser hangs after a while

### Operating system

macOS

### Steps to reproduce

1. Visit https://2gis.ru/moscow
2. Wait
3. Browser hangs

### Expected behavior

Browser doesn't hang

### Actual behavior

Browser hangs

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
2024-11-12 02:49:52.040 Ladybird[40742:4655643] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-12 02:49:52.111 Ladybird[40742:4655643] +[IMKInputSession subclass]: chose IMKInputSession_Modern
174533.445 WebContent(40745): ResourceLoader: Refusing to prefetch DNS for 'https://www.google-analytics.com/': URL was filtered
174533.445 WebContent(40745): ResourceLoader: Refusing to prefetch DNS for 'https://mc.yandex.ru/': URL was filtered
174533.445 WebContent(40745): FIXME: Implement 'Content-Security-Policy' http-equiv state
174533.490 WebContent(40745): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtag/js?id=G-RYXLFPYJB8"
174533.492 WebContent(40745): ResourceLoader: Filtered request to: "https://mc.yandex.ru/metrika/tag.js"
174533.493 WebContent(40745): ResourceLoader: Filtered request to: "https://counter.yadro.ru/hit;2gis/online/ru/moscow?t38.6;r;s720*450*24;uhttps%3A%2F%2F2gis.ru%2Fmoscow0.9262478099964204"
174533.536 WebContent(40745): HTMLScriptElement: Refusing to run script because the element's result is null.
174533.536 WebContent(40745): HTMLScriptElement: Refusing to run script because the element's result is null.
174534.287 WebContent(40745): FIXME: Unimplemented Navigator.maxTouchPoints
174537.494 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174537.496 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174537.692 WebContent(40745): Unhandled JavaScript exception: [ReferenceError] 'XPathResult' is not defined
174537.692 WebContent(40745):     at https://top-fwz1.mail.ru/js/dyn-goal-config.js?ids=3514482:5:337
    at https://top-fwz1.mail.ru/js/dyn-goal-config.js?ids=3514482:7:508

174537.775 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174537.775 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174537.776 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174537.776 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174537.777 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174537.777 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174539.238 WebContent(40745): ImageDecoderClient: Failed to decode image with ID 6: Decoding failed: Could not find suitable image decoder plugin for data
174539.242 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174539.242 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174539.246 WebContent(40745): Potential FIXME: Creating unknown generic element 'parsererror' in namespace 'http://www.mozilla.org/newlayout/xml/parsererror.xml'
174539.445 WebContent(40745): Unhandled JavaScript exception (in promise): [InternalError] TODO(Run Service Worker is not implemented in LibJS)
174539.445 WebContent(40745):
174539.473 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.475 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.477 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.478 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.480 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.482 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.483 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.485 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.487 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.488 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.490 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.495 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.496 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.498 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.500 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.507 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.509 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.510 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.512 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
174539.913 WebContent(40745): ResourceLoader: Filtered request to: "https://www.google-analytics.com/analytics.js"
174539.943 WebContent(40745): HTMLScriptElement: Refusing to run script because the element's result is null.
174541.327 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
174582.956 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
174624.787 WebContent(40745): FIXME: Stubbed ScreenOrientation::type()
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
```
```


### Screenshots or screen recordings

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/2ddf7dec-5522-4736-b8f4-889aec480e77">


### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by shlyakpavel** [comment]
With recent changes, it no more renders
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/e00bef7d-03fc-49b0-832e-25a96ceda766" />

**Comment by shlyakpavel** [comment]
The log is now
```
2025-01-26 08:13:12.913 Ladybird[1968:5403575] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-26 08:13:13.021 Ladybird[1968:5403575] +[IMKInputSession subclass]: chose IMKInputSession_Modern
556146.574 WebContent(1971): ResourceLoader: Refusing to prefetch DNS for 'https://www.google-analytics.com/': URL was filtered
556146.574 WebContent(1971): ResourceLoader: Refusing to prefetch DNS for 'https://mc.yandex.ru/': URL was filtered
556146.575 WebContent(1971): FIXME: Implement 'Content-Security-Policy' http-equiv state
556146.630 WebContent(1971): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtag/js?id=G-RYXLFPYJB8"
556146.632 WebContent(1971): ResourceLoader: Filtered request to: "https://mc.yandex.ru/metrika/tag.js"
556146.633 WebContent(1971): ResourceLoader: Filtered request to: "https://counter.yadro.ru/hit;2gis/online/ru/moscow?t38.6;r;s720*450*24;uhttps%3A%2F%2F2gis.ru%2Fmoscow0.5960700394576578"
556146.694 WebContent(1971): HTMLScriptElement: Refusing to run script because the element's result is null.
556146.694 WebContent(1971): HTMLScriptElement: Refusing to run script because the element's result is null.
556152.230 WebContent(1971): FIXME: Unimplemented Navigator.maxTouchPoints
556155.099 WebContent(1971): FIXME: Unimplemented IDL interface: 'NavigatorPrototype.registerProtocolHandler'
556155.099 WebContent(1971): FIXME: Unimplemented IDL interface: 'NavigatorPrototype.unregisterProtocolHandler'
556155.099 WebContent(1971): FIXME: Unimplemented Navigator.maxTouchPoints
556155.102 WebContent(1971): FIXME: Stubbed ScreenOrientation::angle()
556155.102 WebContent(1971): FIXME: Stubbed ScreenOrientation::type()
556155.102 WebContent(1971): FIXME: Unimplemented Screen::is_extended
556155.106 WebContent(1971): FIXME: Unimplemented IDL interface: 'IDBDatabasePrototype.createObjectStore'
556155.106 WebContent(1971): (js error) [TypeError] undefined is not a function (evaluated from '<object>.createObjectStore')
556155.107 WebContent(1971): FIXME: Unimplemented IDL interface: 'IDBDatabasePrototype.transaction'
556155.110 WebContent(1971): (js error) [TypeError] undefined is not a function (evaluated from '<object>.createObjectStore')
556155.110 WebContent(1971): Unhandled JavaScript exception (in promise): [TypeError] undefined is not a function (evaluated from 'e.transaction')
556155.110 WebContent(1971):     at <unknown>
    at <unknown>

556155.326 WebContent(1971): FIXME: Implement Audio::connect(AudioNode)
556155.326 WebContent(1971): FIXME: Implement Audio::connect(AudioNode)
556155.326 WebContent(1971): FIXME: Implement Audio::connect(AudioNode)
556155.445 WebContent(1971): FIXME: Unimplemented IDL interface: 'SVGTextContentElementPrototype.getComputedTextLength'
556155.651 WebContent(1971): Unknown WebGL parameter name: 8824
556155.653 WebContent(1971): Unknown WebGL parameter name: c23
556155.653 WebContent(1971): Unknown WebGL parameter name: 86a3
556155.653 WebContent(1971): Unknown WebGL parameter name: 9243
556155.653 WebContent(1971): Unknown WebGL parameter name: 9240
556155.653 WebContent(1971): Unknown WebGL parameter name: 9241
556155.656 WebContent(1971): Unknown WebGL parameter name: c23
556155.656 WebContent(1971): Unknown WebGL parameter name: 86a3
556155.656 WebContent(1971): Unknown WebGL parameter name: 8825
556155.656 WebContent(1971): Unknown WebGL parameter name: 8826
556155.656 WebContent(1971): Unknown WebGL parameter name: 8827
556155.656 WebContent(1971): Unknown WebGL parameter name: 8828
556155.656 WebContent(1971): Unknown WebGL parameter name: 8829
556155.656 WebContent(1971): Unknown WebGL parameter name: 882a
556155.656 WebContent(1971): Unknown WebGL parameter name: 882b
556155.656 WebContent(1971): Unknown WebGL parameter name: 882c
556155.656 WebContent(1971): Unknown WebGL parameter name: 8b8b
556155.656 WebContent(1971): Unknown WebGL parameter name: 9247
556155.656 WebContent(1971): Unknown WebGL parameter name: d02
556155.656 WebContent(1971): Unknown WebGL parameter name: d04
556155.656 WebContent(1971): Unknown WebGL parameter name: d03
556155.656 WebContent(1971): Unknown WebGL parameter name: 8c89
556155.656 WebContent(1971): Unknown WebGL parameter name: c02
556155.656 WebContent(1971): Unknown WebGL parameter name: 8e24
556155.656 WebContent(1971): Unknown WebGL parameter name: 8e23
556155.656 WebContent(1971): Unknown WebGL parameter name: 9243
556155.656 WebContent(1971): Unknown WebGL parameter name: 9240
556155.656 WebContent(1971): Unknown WebGL parameter name: 806e
556155.656 WebContent(1971): Unknown WebGL parameter name: 9241
556155.656 WebContent(1971): Unknown WebGL parameter name: cf2
556155.656 WebContent(1971): Unknown WebGL parameter name: 806d
556155.656 WebContent(1971): Unknown WebGL parameter name: cf4
556155.656 WebContent(1971): Unknown WebGL parameter name: cf3
556157.643 WebContent(1971): Unhandled JavaScript exception (in promise): [TypeError] undefined is not a function (evaluated from 'e.transaction')
556157.643 WebContent(1971):     at <unknown>
    at <unknown>

556158.096 WebContent(1971): FIXME: Stubbed ScreenOrientation::type()
556158.099 WebContent(1971): FIXME: Stubbed ScreenOrientation::type()
```
2gis definitely felt better w/o WebGL, at least it could render the map.

**Comment by shlyakpavel** [comment]
It's actually getting worse

<img width="1359" alt="Image" src="https://github.com/user-attachments/assets/9a3128da-11a5-4a31-b2d6-ede0e1e5d63c" />

**Comment by shlyakpavel** [comment]
Now it's back to https://github.com/LadybirdBrowser/ladybird/issues/2291#issuecomment-2543127209
Partially blocked by https://github.com/LadybirdBrowser/ladybird/pull/6262

**Comment by shlyakpavel** [comment]
Now it renders and hangs with
```
350112.068 WebContent(69081): ResourceLoader: Refusing to prefetch DNS for 'https://www.google-analytics.com/': URL was filtered
350112.068 WebContent(69081): ResourceLoader: Refusing to prefetch DNS for 'https://mc.yandex.ru/': URL was filtered
350112.114 WebContent(69081): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtag/js?id=G-RYXLFPYJB8"
350112.117 WebContent(69081): ResourceLoader: Filtered request to: "https://mc.yandex.ru/metrika/tag.js"
350112.117 WebContent(69081): ResourceLoader: Filtered request to: "https://counter.yadro.ru/hit;2gis/online/ru/moscow?t38.6;r;s1440*900*24;uhttps%3A%2F%2F2gis.ru%2Fmoscow0.4011114776908927"
350112.145 WebContent(69081): HTMLScriptElement: Refusing to run script because the element's result is null.
350112.145 WebContent(69081): HTMLScriptElement: Refusing to run script because the element's result is null.
350112.603 WebContent(69081): FIXME: Implement AudioScheduledSourceNode::start
350112.816 WebContent(69081): FIXME: Unimplemented Navigator.maxTouchPoints
350113.104 WebContent(69081): Unhandled JavaScript exception (in promise): InvalidStateError: Rendering is already started
350113.604 WebContent(69081): Unhandled JavaScript exception (in promise): InvalidStateError: Rendering is already started
350115.664 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350115.667 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350128.969 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.969 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.969 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.969 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.970 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.970 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.970 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.970 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.970 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.970 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.970 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.970 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.971 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.971 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.971 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.971 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.971 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.971 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.971 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.971 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.972 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.972 WebContent(69081):     at Error
    at sl (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:118337)
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:191086)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173610)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350128.972 WebContent(69081): Unhandled JavaScript exception: [Error] Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
350128.972 WebContent(69081):     at Error
    at xi (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:190775)
    at bs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178656)
    at vs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178584)
    at gs (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:178447)
    at ls (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:175282)
    at as (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:173837)
    at S (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200444)
    at R (https://d-assets.2gis.ru/react.3cd37cb30cc8d5ff356b.js:1:200976)
    at <unknown>
    at <unknown>
    at <unknown>

350129.021 WebContent(69081): ResourceLoader: Failed load of: "https://ext.clickstream.sberbank.ru/metrics/ecosystem/2gis", Error: SSL verification failed (status: 0), Duration: 486ms
350129.054 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.055 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.055 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.056 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.056 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.057 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.057 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.058 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.058 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.059 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.060 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.060 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.061 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.062 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.062 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.063 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.063 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.065 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.066 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.067 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.068 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.069 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350129.103 WebContent(69081): Unhandled JavaScript exception (in promise): [TypeError] CORS-preflight check failed
350129.103 WebContent(69081):
350129.365 WebContent(69081): Unhandled JavaScript exception (in promise): [InternalError] TODO(Run Service Worker is not implemented in LibJS)
350129.365 WebContent(69081):
350129.792 WebContent(69081): ThreadEventQueue::process: Job queue wasn't designed for this load (31 promises)
350130.148 WebContent(69081): SVGFilterElement::gfx_filter(): Unknown or unsupported filter element 'femorphology'
350130.306 WebContent(69081): ImageDecoderClient: Failed to decode image with ID 8: Decoding failed: Could not find suitable image decoder plugin for data
350130.949 WebContent(69081): FIXME: Stubbed ScreenOrientation::type()
350130.979 WebContent(69081): FIXME: Handle null navigation_request in navigation response Content Security Policy check.
350131.483 WebContent(69081): (js warn) "Deprecated property or method 'AbstractLoader.IMAGE'. See docs for info."
```

<img width="1326" height="831" alt="Image" src="https://github.com/user-attachments/assets/fc3f1d1e-d6ac-4cd2-9c12-1d0ba47d4a28" />
