### ISSUE TITLE
LibWeb: Segfault in WPT legend display test

### ISSUE THREAD

**Issue by tcl3** [LadybirdBrowser/ladybird#2452]
### Summary

The following WPT test now crashes with a segfault: http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display.html

Bisected to: a820308a02957887e3e979c3b034549f83003c32 and/or the followup commit c47d19d05a34af3eb0bcdad00f62bfb5ea1a9f50

### Operating system

Linux

### Steps to reproduce

1. Open http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display.html
2. :boom: 

### Expected behavior

No crash

### Actual behavior

A segfault occurs

### URL for a reduced test case

http://wpt.live/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display.html

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
#0  0x00007b054951d998 in fast_is<Web::Layout::TextNode> ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/TextNode.h:78
#1  is<Web::Layout::TextNode, Web::Layout::Node const> ()
    at /home/tim/repos/ladybird/AK/TypeCasts.h:21
#2  next_without_lookahead ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:208
#3  0x00007b054951d928 in next ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:140
#4  0x00007b054951b341 in generate_line_boxes ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:266
#5  0x00007b054951b16c in run ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:85
#6  0x00007b05494f7c79 in layout_inside ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/FormattingContext.cpp:244
#7  0x00007b054951c58d in dimension_box_on_line ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:186
#8  0x00007b054951da47 in next_without_lookahead ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:362
#9  0x00007b054951d928 in next ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:140
#10 0x00007b054951b341 in generate_line_boxes ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:266
#11 0x00007b054951b16c in run ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:85
#12 0x00007b05494f7c79 in layout_inside ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/FormattingContext.cpp:244
#13 0x00007b054951c58d in dimension_box_on_line ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:186
#14 0x00007b054951da47 in next_without_lookahead ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:362
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007b054951d928 in next ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:140
#16 0x00007b054951b341 in generate_line_boxes ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:266
#17 0x00007b054951b16c in run ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:85
#18 0x00007b05494f7c79 in layout_inside ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/FormattingContext.cpp:244
#19 0x00007b054951c58d in dimension_box_on_line ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:186
#20 0x00007b054951da47 in next_without_lookahead ()
    at /home/tim/repos/ladybird/Libraries/LibWeb/Layout/InlineLevelIterator.cpp:362
(33077 further stack frames omitted)
```

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by tcl3** [comment]
This test has been fixed
