### ISSUE TITLE
hsedesign.ru crashes Ladybird

### ISSUE THREAD

**Issue by shlyakpavel** [LadybirdBrowser/ladybird#2475]
### Summary

When I open hsedesign.ru in Ladybird, it crashes

### Operating system

macOS

### Steps to reproduce

1. Open Ladybird
2. Navigate to hsedesign.ru
3. Observe

### Expected behavior

It doesn't crash

### Actual behavior

It crashes

### URL for a reduced test case

hsedesign.ru

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
2024-11-21 11:09:55.391 Ladybird[86654:1655926] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-21 11:09:55.439 Ladybird[86654:1655926] +[IMKInputSession subclass]: chose IMKInputSession_Modern
71338.373 WebContent(86657): (js log) "ym init for" "hsedesign.ru"
71338.373 WebContent(86657): Unhandled JavaScript exception: [TypeError] https://hsedesign.ru/ is not a function (evaluated from '<object>.href')
71338.373 WebContent(86657):     at https://hsedesign.ru/:1:2287
    at <unknown>
    at https://hsedesign.ru/:1:1

71338.375 WebContent(86657): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtm.js?id=GTM-NL8PKVH"
71338.375 WebContent(86657): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtag/js?id=G-DPXM9GVYLS"
71338.375 WebContent(86657): ResourceLoader: Filtered request to: "https://mc.yandex.ru/metrika/tag.js"
71338.375 WebContent(86657): HTMLScriptElement: Refusing to run script because the element's result is null.
71338.375 WebContent(86657): HTMLScriptElement: Refusing to run script because the element's result is null.
71338.375 WebContent(86657): HTMLScriptElement: Refusing to run script because the element's result is null.
71339.118 WebContent(86657): FIXME: Unimplemented Navigator.maxTouchPoints
71339.288 WebContent(86657): Unhandled JavaScript exception: [ReferenceError] 'XPathResult' is not defined
71339.288 WebContent(86657):     at https://top-fwz1.mail.ru/js/dyn-goal-config.js?ids=3566743:5:337
    at https://top-fwz1.mail.ru/js/dyn-goal-config.js?ids=3566743:7:508

71339.737 WebContent(86657): Failed to parse font: Automatic format detection failed
71345.772 WebContent(86657): FIXME: Unimplemented IDL interface: 'ServiceWorkerContainerPrototype.ready'
71345.772 WebContent(86657): Unhandled JavaScript exception: [TypeError] Cannot access property "then" on undefined object "navigator.serviceWorker.ready"
71345.772 WebContent(86657):     at https://hsedesign.ru/brg/static/js/main.73902fbe.js:33706:21195
    at https://hsedesign.ru/brg/static/js/main.73902fbe.js:33706:21195
    at https://hsedesign.ru/brg/static/js/main.73902fbe.js:33706:21195

71345.773 WebContent(86657): FIXME: Unimplemented IDL interface: 'LocationPrototype.ancestorOrigins'
71345.773 WebContent(86657): FIXME: Unimplemented IDL interface: 'LocationPrototype.ancestorOrigins'
71345.773 WebContent(86657): (js log) "StartRoutingMiniApps!!!" "hsedesign.ru" Location{ "href": "https://hsedesign.ru/", "origin": "https://hsedesign.ru", "protocol": "https:", "host": "hsedesign.ru", "hostname": "hsedesign.ru", "port": "", "pathname": "/", "search": "", "hash": "", "ancestorOrigins": undefined, "reload": [NativeFunction] , "replace": [NativeFunction] , "assign": [NativeFunction] , "toString": [NativeFunction]  } "/"
71345.774 WebContent(86657): (js log) "Приложение успешно найдено" Object{ "host": "hsedesign.ru", "mode": "production", "application": "deziiign/hsedesign" } Object{ "authentication": Object{ "App": [Function] App, "manifest": Object{ "title": "Burgundy Authorization", "reducer": Object{}, "auth": Object{ "productionClientId": "", "developClientId": "" }, "clear": true } }, "team": Object{ "App": [Function] App, "manifest": Object{ "title": "Team", "reducer": Object{}, "theme": Object{ "accent": Object{ "colorA": "", "colorB": "", "colorC": "", "colorD": "" }, "app": Object{ "backgroundColor": "#2A3034", "text": "#FEFEFE", "ten": "#545453" }, "tabs": Object{ "gradient": "#2A3034" }, "peoplePage": Object{ "title": Object{ "color": "#fff" } }, "mainSearchBar": Object{ "bg": "#3F4548", "placeholder": Object{ "color": "#909090" }, "input": Object{ "bg": "#3F4548", "placeholder": Object{ "color": "#575B5E" } }, "text": Object{ "color": "#FEFEFE", "hover": Object{ "color": "#353A3E" } }, "tabs": Object{ "color": "#909090", "colorActive": "#fefefe" } }, "longreadTranslated": Object{ "bg": "rgba(144, 144, 144, 0.8)", "color": "rgba(254, 254, 254, 1)" }, "mainSearchBarFooter": Object{ "bg": "#2A3034", "placeholder": Object{ "color": "#909090" } }, "educationSearchBar": Object{ "result": Object{ "color": "#fff" } }, "mainDropdownStyles": Object{ "colorActive": "#151514", "color": "#fefefe", "bg": "#3F4548", "hoverBG": "#575B5E" }, "mainBg": "#2A3034", "loading": "#8E9193", "tagView": Object{ "titleColor": "#FEFEFE", "goToMediaColor": "#FEFEFE", "goToMediaHoverColor": "#6C7073" }, "longread": Object{ "border": "none", "fontSize": "", "lineHeight": "" }, "progressbar": Object{ "color": "#8E9193", "colorBold": "#FEFEFE", "borderColor": "#6C7073" } undefined
71345.928 WebContent(86657): (js info) "[UserManager] getUser:" "user not found in storage"
71346.027 WebContent(86657): No property (from 2 properties) matched Token: Ident: px
71346.027 WebContent(86657):     row-gap
71346.027 WebContent(86657):     column-gap
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.063 WebContent(86657): (js log) "location found"
71346.137 WebContent(86657): Failed to parse font: Automatic format detection failed
71346.137 WebContent(86657): Failed to parse font: Automatic format detection failed
71346.187 WebContent(86657): FIXME: Implement Audio::connect(AudioNode)
71346.187 WebContent(86657): FIXME: Implement Audio::connect(AudioNode)
71346.196 WebContent(86657): FIXME: Unimplemented IDL interface: 'CanvasRenderingContext2DPrototype.globalCompositeOperation'
71346.223 WebContent(86657): FIXME: Unimplemented Navigator.maxTouchPoints
71346.223 WebContent(86657): FIXME: Unimplemented Navigator.maxTouchPoints
71346.418 WebContent(86657): (js log) "Uploader initialization..."
71346.460 WebContent(86657): (js log) "tst" undefined false
71346.632 Ladybird(86654): WebContent process crashed! Last page loaded: https://hsedesign.ru/
71346.632 Ladybird(86654): Consider raising an issue at https://github.com/LadybirdBrowser/ladybird/issues/new/choose
71362.706 WebContent(86684): ConnectionBase::send_thread: send: Broken pipe (errno=32)
71362.932 Ladybird(86654): mach_msg failed: (ipc/rcv) port changed
```

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by shlyakpavel** [comment]
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xcc)
  * frame #0: 0x00000001069ba298 liblagom-web.0.0.0.dylib`::broadcast_active_resize_observations() [inlined] clear_with_capacity at Vector.h:375:16 [opt]
    frame #1: 0x00000001069ba298 liblagom-web.0.0.0.dylib`::broadcast_active_resize_observations() [inlined] clear at Vector.h:363:9 [opt]
    frame #2: 0x00000001069ba298 liblagom-web.0.0.0.dylib`::broadcast_active_resize_observations() at Document.cpp:5210:36 [opt]
    frame #3: 0x0000000106aa123c liblagom-web.0.0.0.dylib`::update_the_rendering() at EventLoop.cpp:350:51 [opt]
    frame #4: 0x0000000106819f20 liblagom-web.0.0.0.dylib`::operator()() at Function.h:120:25 [opt]
    frame #5: 0x0000000106aa0a24 liblagom-web.0.0.0.dylib`::process() at EventLoop.cpp:177:22 [opt]
    frame #6: 0x0000000106819f20 liblagom-web.0.0.0.dylib`::operator()() at Function.h:120:25 [opt]
    frame #7: 0x0000000105003318 liblagom-core.0.0.0.dylib`::operator()() at Function.h:120:25 [opt]
    frame #8: 0x00000001050028f0 liblagom-core.0.0.0.dylib`::dispatch_event() at EventReceiver.cpp:162:17 [opt]
    frame #9: 0x0000000105011728 liblagom-core.0.0.0.dylib`::process() at ThreadEventQueue.cpp:121:23 [opt]
    frame #10: 0x0000000105013948 liblagom-core.0.0.0.dylib`::exec() [inlined] pump at EventLoopImplementationUnix.cpp:324:40 [opt]
    frame #11: 0x0000000105013934 liblagom-core.0.0.0.dylib`::exec() at EventLoopImplementationUnix.cpp:316:9 [opt]
    frame #12: 0x000000010500064c liblagom-core.0.0.0.dylib`::exec() at EventLoop.cpp:88:20 [opt]
    frame #13: 0x0000000104a7d56c WebContent`::serenity_main() at main.cpp:208:23 [opt]
    frame #14: 0x0000000104b1510c WebContent`main at Main.cpp:39:19 [opt]
    frame #15: 0x0000000183164274 dyld`start + 2840
```
Looks undebuggable

**Comment by shlyakpavel** [comment]
I guess it might be the same issue as https://github.com/LadybirdBrowser/ladybird/issues/2011
