### ISSUE TITLE
reliable crash testing privacy hooks at https://coveryourtracks.eff.org/

### ISSUE THREAD

**Issue by pfrench42** [LadybirdBrowser/ladybird#338]
navigated here to run a batch of privacy tests:

```
254630.427 WebContent(794842): Web::EventHandler: Clicking on a link to https://coveryourtracks.eff.org/kcarter?aat=1
VERIFICATION FAILED: m_ptr at /home/me/proj/github/ladybird/Userland/Libraries/LibJS/Heap/GCPtr.h:168
```

**Comment by utf-4096** [comment]
Was able to reproduce (although it took a few tries). On commit e76ad9492e

```
5172.002 WebContent(4151): Process {/opt/ladybird/Build/ladybird/libexec/WebContent} with pid 4151 is sleeping, waiting for debugger.
5197.288 WebContent(4151): Web::EventHandler: Clicking on a link to https://coveryourtracks.eff.org/kcarter-nojs
5197.926 WebContent(4151): ResourceLoader: Failed load of: "https://coveryourtracks.eff.org/js/?idsite=40&rec=1&urlref=&action_name=Cover%20Your%20Tracks", Error: Load failed: 404, Duration: 277ms
5198.266 WebContent(4151): ImageDecoderClient: Failed to decode image with ID 1: Decoding failed: Could not find suitable image decoder plugin for data
VERIFICATION FAILED: m_ptr at /opt/ladybird/Userland/Libraries/LibJS/Heap/GCPtr.h:168
```

GDB backtrace:
```
#0  ak_verification_failed () at /opt/ladybird/AK/Assertions.cpp:102
#1  0x00007feb65aa7af0 in JS::GCPtr<Web::DOM::Document>::operator-> () at /opt/ladybird/Userland/Libraries/LibJS/Heap/GCPtr.h:168
#2  operator() () at /opt/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:3036
#3  for_each_shadow_including_inclusive_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> >(void) ()
    at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:103
#4  0x00007feb65aa7a77 in for_each_shadow_including_inclusive_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> >(void) ()
    at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:112
#5  0x00007feb65aa7a77 in for_each_shadow_including_inclusive_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> >(void) ()
    at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:112
#6  0x00007feb65aa7a77 in for_each_shadow_including_inclusive_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> >(void) ()
    at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:112
#7  0x00007feb65aa7c47 in for_each_shadow_including_inclusive_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> > ()
    at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:112
#8  for_each_shadow_including_descendant<Web::DOM::Document::descendant_navigables()::<lambda(Web::DOM::Node&)> >(void) () at /opt/ladybird/Userland/Libraries/LibWeb/DOM/ShadowRoot.h:128
#9  0x00007feb65aa7d4b in Web::DOM::Document::descendant_navigables () at /opt/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:3028
#10 Web::DOM::Document::descendant_navigables () at /opt/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:3047
#11 Web::DOM::Document::anything_is_delaying_the_load_event () at /opt/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:2829
#12 0x00007feb65cdb020 in operator() () at /opt/ladybird/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:321
#13 call () at /opt/ladybird/Userland/Libraries/LibJS/SafeFunction.h:133
#14 0x00007feb65becf81 in JS::SafeFunction<bool ()>::operator()() const () at /opt/ladybird/Userland/Libraries/LibJS/SafeFunction.h:85
#15 operator() () at /opt/ladybird/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:86
#16 call () at /opt/ladybird/Userland/Libraries/LibJS/SafeFunction.h:133
#17 0x00007feb65eb3899 in JS::SafeFunction<bool ()>::operator()() const () at /opt/ladybird/Userland/Libraries/LibJS/SafeFunction.h:85
#18 AK::Function<bool ()>::CallableWrapper<JS::SafeFunction<bool ()> >::call() () at /opt/ladybird/AK/Function.h:187
#19 0x00007feb673c6547 in AK::Function<bool ()>::operator()() const () at /opt/ladybird/AK/Function.h:120
#20 Core::EventLoop::spin_until(AK::Function<bool ()>) () at /opt/ladybird/Userland/Libraries/LibCore/EventLoop.cpp:94
#21 0x00007feb65eb2c27 in Web::Platform::EventLoopPluginSerenity::spin_until(JS::SafeFunction<bool ()>) ()
    at /opt/ladybird/Userland/Libraries/LibWeb/Platform/EventLoopPluginSerenity.cpp:19
#22 0x00007feb65beca25 in Web::HTML::EventLoop::spin_until(JS::SafeFunction<bool ()>) () at /opt/ladybird/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:85
#23 0x00007feb65cf7939 in Web::HTML::HTMLParser::the_end () at /opt/ladybird/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:320
#24 0x00007feb65cf7ed1 in Web::HTML::HTMLParser::run () at /opt/ladybird/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:227
#25 0x00007feb65eb3999 in JS::SafeFunction<void ()>::operator()() const () at /opt/ladybird/Userland/Libraries/LibJS/SafeFunction.h:85
#26 AK::Function<void ()>::CallableWrapper<JS::SafeFunction<void ()> >::call() () at /opt/ladybird/AK/Function.h:187
#27 0x00007feb673ea55a in AK::Function<void ()>::operator()() const () at /opt/ladybird/AK/Function.h:120
#28 Core::ThreadEventQueue::process () at /opt/ladybird/Userland/Libraries/LibCore/ThreadEventQueue.cpp:118
#29 0x0000558c987b80dd in Ladybird::EventLoopManagerQt::event_target_received_event () at /opt/ladybird/Ladybird/Qt/EventLoopImplementationQt.cpp:325
#30 0x0000558c987bb68e in Ladybird::EventLoopImplementationQtEventTarget::event () at /opt/ladybird/Ladybird/Qt/EventLoopImplementationQtEventTarget.cpp:13
#31 0x00007feb675626af in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#32 0x00007feb67565e67 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt6Core.so.6
#33 0x00007feb677c1aa3 in ?? () from /usr/lib/libQt6Core.so.6
#34 0x00007feb61110cc4 in ?? () from /usr/lib/libglib-2.0.so.0
#35 0x00007feb61113d47 in ?? () from /usr/lib/libglib-2.0.so.0
#36 0x00007feb6111433c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#37 0x00007feb677c133c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#38 0x00007feb6756e173 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#39 0x00007feb673c66d6 in Core::EventLoop::exec () at /opt/ladybird/Userland/Libraries/LibCore/EventLoop.cpp:88
#40 0x0000558c987c7cfa in serenity_main () at /opt/ladybird/Ladybird/WebContent/main.cpp:196
#41 0x0000558c98895d82 in main () at /opt/ladybird/Userland/Libraries/LibMain/Main.cpp:43
```

**Comment by AtkinsSJ** [comment]
Managed to get a crash but it looks like a different one?

```
VERIFICATION FAILED: false at /home/sam/Projects/ladybird/Userland/Libraries/LibWeb/HTML/Navigable.cpp:509
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x732ea577beaf]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::Navigable::get_session_history_entries() const 0x461) [0x732ea9a57c61]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0 Web::HTML::finalize_a_cross_document_navigation(JS::NonnullGCPtr<Web::HTML::Navigable>, Web::HTML::HistoryHandlingBehavior, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>) 0x99) [0x732ea9a60489]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0xc63e52) [0x732ea9a63e52]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0x942f1f) [0x732ea9742f1f]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-web.so.0(+0xcc6154) [0x732ea9ac6154]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0(+0x3668f) [0x732ea8dd668f]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x75) [0x732ea8dd5b65]
/home/sam/Projects/ladybird/Build/ladybird/libexec/WebContent(+0x850b0) [0x5dc3e65580b0]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x183d9b) [0x732eaaf83d9b]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimer::timeout(QTimer::QPrivateSignal) 0x3d) [0x732eaaf8ed6d]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QObject::event(QEvent*) 0x1c6) [0x732eaaf76576]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xf6) [0x732eaaf38416]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x36b) [0x732eab07b7ab]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x333a29) [0x732eab133a29]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5d5b5) [0x732ea51145b5]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbc717) [0x732ea5173717]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x732ea5113a53]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x6f) [0x732eab1315ef]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x2e3) [0x732eaaf429a3]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoop::exec() 0x37) [0x732ea8dce2c7]
/home/sam/Projects/ladybird/Build/ladybird/libexec/WebContent(+0x911a6) [0x5dc3e65641a6]
/home/sam/Projects/ladybird/Build/ladybird/libexec/WebContent(+0x13f812) [0x5dc3e6612812]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x732ea4e2a1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x732ea4e2a28b]
/home/sam/Projects/ladybird/Build/ladybird/libexec/WebContent(+0x83605) [0x5dc3e6556605]
```

**Comment by shlyakpavel** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3c3502e9-d303-462a-b557-d068233815bb">
A few tries didn't crash it for me
macOS, f80fca2deeb2b0ea5ffd0af714bcd79b3ad729dd

**Comment by shannonbooth** [comment]
Can no longer repro
